NUMPY GİRİŞ : 

In [1]:
# NUMERİC python kısaltılmasıdır. Bilimsel ve istatiksel ihtiyaçları hesaplamak için kullanılan ileri düzey bir özellikti

In [3]:
# Neden numpy:
# ör: iki dizinin çarpımlarını bir dizi içine ekleyip gösteriniz:
a=[3,5,7]
b=[2,4,6]
ab=[]
carpım=1
for x,y in zip(a,b):
    carpım=x*y
    ab.append(carpım)
print(ab)    


[6, 20, 42]


In [4]:
# bunu bir de numpy ile yaparsak:

In [2]:
import numpy as np # numpy import edildi. Ben np kısaltmasını kullanıyorum. isteyen farklı bir değer yazabilir.

In [6]:
a=np.array([3,5,7])
b=np.array([2,4,6])
c=np.array([8,9,10])
d=a*b*c
print(list(d))
# numpy ile istediğiniz kadar listeyi birlikte işleme sokabilirsiniz.

[48, 180, 420]


SIFIRDAN NUMPY ARRAYİ OLUŞTURMA:

In [7]:
# 1-) ilk önce import numpy as np ile numpy import edilir. Yukarıda oluşturduğumuz için yazmadım.

In [8]:
x= np.array([1,2,3,4,5])

In [9]:
type(x) # tipi numpy.ndarray olur.

numpy.ndarray

In [10]:
np.array([2,3.14,5,6]) # numpy sadece tek tip bilgi tutar. Float değer kullanıldığı için hepsini float çevirdi.

array([2.  , 3.14, 5.  , 6.  ])

In [11]:
np.array([2,3.14,5,6], dtype="int") # tüm değerleri int değerine çevirir.

array([2, 3, 5, 6])

In [14]:
np.array([2,3.14,5,6], dtype="str") # tüm değerleri string değer olarak gösterir.

array(['2', '3.14', '5', '6'], dtype='<U4')

In [15]:
# Sıfırdan array oluşturma:

In [16]:
np.zeros(10) # 10 tane 0 değeri float şeklinde oluştu.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10,dtype="int") # 10 tane int türünde 1 oluştu.

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
# çift boyutlu matris:
np.ones((3,5 ),dtype="int") # 3 satır 5 sutundan oluşan 1 rakamlarını oluşturdu.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full((3,5),3) # sadece 3 rakamından 3 satır 5 sutundan oluşan matris. Burda 3 ü direk belirttiğimiz için dtype demedik.

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
np.arange(1,22,2) # tek boyutlu. 1-22 arasında 2 şer şer artan sayıları oluşturur. arange int oluşturur.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [25]:
np.linspace(1,2,10) # 1-2 arasında float tipinde 10 adet sayı oluşturur.

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [28]:
# Örneğin, bir sınava ait sonuç seti 10, 8, 10, 8, 8 ve 4 olsun.
    # 1-) Aritmetik ortalama: 
    # 10+8+10+8+8+4 = 48
    # 48/6=8 8 aritmetik ortalamadır. 6 adet sayı olduğu için 6 ya böldük.
    
    # 2-) Varyansı Bulma : 
    # aritmetik ortalama = 8 tüm sayılardan 8 'i teker teker çıkaracağız. 
    #ilk önce: 10-8, 8-8, 10-8, 8-8, 8-8, 4-8,
    # sonrasında sonuçların karelerini al ve alınan karelerin toplamını kaç adet sayı varsa onun 1 eksiğine bölerek varyansı buluruz.
    # 2**2 + 0**2 + 2**2 + 0**2 + 0**2 + -4**2 = 24. 6 adet sayı var. 6-1=5. 24/5 = 4,8 varyans değerdir
    
    # 3-) Standart sapma hesaplama : 
    # varyans değerin karekökü standart sapmayı verir.
    # 4.8 in karekökü 2.19 dur. Standat sapma 2.19 dur.
    


In [31]:
np.random.normal(10,4,(2,3)) # ortalaması 10 standart sapması 4 olan 2 satır 3 sutunluk bir matris oluşturduk.

array([[11.05787975,  2.54305088, 14.22761478],
       [17.85580149,  3.66861586,  8.12029971]])

In [32]:
np.random.randint(0,10,(2,3)) # 0-10 arası 2 satır 3 sutunluk rastgele sayılar oluşturdu.

array([[9, 4, 1],
       [6, 3, 2]])

In [33]:
# Numpy Array Özellikleri:

In [34]:
a = np.random.randint(10, size=9)

In [35]:
print(a)

[0 5 5 8 9 1 3 5 0]


In [37]:
a.ndim # boyut bilgisini verir. 1 yani tek boyutlu.

1

In [38]:
a.size # bize eleman sayısını verir.

9

In [39]:
a.shape # 9 tane eleman var dendi.

(9,)

In [40]:
a.dtype

dtype('int32')

In [43]:
x=np.random.randint(10, size=(2,3))

In [44]:
print(x)

[[3 4 2]
 [4 8 1]]


In [45]:
x.ndim

2

In [46]:
x.size

6

In [47]:
x.shape

(2, 3)

In [48]:
x.dtype

dtype('int32')

In [49]:
#reshape:
a=np.arange(1,10)

In [50]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [54]:
a.reshape(3,3) # reshape fonksiyonu tek boyutluyu çok boyuta çevirir. eleman sayısı 9 olduğu için 3,3 yaptık.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a.reshape(1,9) # bu da çok boyutludur. Çünkü 1 satır 9 sutundan oluşturulur. 

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
# array birleştirme concatenate:
x=np.array([2,4,6])
y=np.array([1,3,5])

In [57]:
np.concatenate([x,y]) # numpy arrayleri birleştirir.

array([2, 4, 6, 1, 3, 5])

In [58]:
z=np.array([7,8,9])

In [60]:
np.concatenate([x,y,z]) # z yide birleştirdi

array([2, 4, 6, 1, 3, 5, 7, 8, 9])

In [62]:
# çok boyutlu concate:
a=np.random.randint(1,10,size=(3,3)) # ilk önce rastgele 3 satır 3 sutun matris oluşturdum.

In [63]:
print(a) # matrisi bastım.

[[7 2 1]
 [1 4 8]
 [6 8 5]]


In [64]:
b=np.array([a]) # sonra matrisi arraye çevirdim. Birleştirme işlemi için.

In [65]:
b # b arrayini elde ettik.

array([[[7, 2, 1],
        [1, 4, 8],
        [6, 8, 5]]])

In [66]:
np.concatenate([b,b]) # b yi iki defa birleştirdi.

array([[[7, 2, 1],
        [1, 4, 8],
        [6, 8, 5]],

       [[7, 2, 1],
        [1, 4, 8],
        [6, 8, 5]]])

In [69]:
np.concatenate([b,b], axis=1) # böyle dersek 1 adet sutun bazında birleştirme işlemi gerçekleşir. Çok tavsiye edilmiyor.

array([[[7, 2, 1],
        [1, 4, 8],
        [6, 8, 5],
        [7, 2, 1],
        [1, 4, 8],
        [6, 8, 5]]])

In [71]:
# array ayırma split:
a=np.arange(1,10)

In [79]:
np.split(a, [2,5]) # bölme işlemine 2 den başla 5 e kadar böl 5 ten sonra bölme demektir.

[array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

In [80]:
a,b,c=np.split(a,[3,5])

In [81]:
a

array([1, 2, 3])

In [82]:
b

array([4, 5])

In [83]:
c

array([6, 7, 8, 9])

In [84]:
x=np.arange(9).reshape(3,3)

In [85]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
np.vsplit(x,[2]) # 2 . index numarasına kadar sutun bazında böler. vsplit()

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]])]

In [89]:
np.hsplit(x,[2]) # 2 . index numarasını dahil etmeden satır bazında böler. hsplit()

[array([[0, 1],
        [3, 4],
        [6, 7]]),
 array([[2],
        [5],
        [8]])]

In [95]:
# sıralama sorted:
x=np.random.randint(1,9,size=7)

In [96]:
x

array([4, 8, 1, 5, 7, 8, 4])

In [97]:
np.sort(x)

array([1, 4, 4, 5, 7, 8, 8])

In [98]:
a=np.random.randint(3,10,size=(3,4))

In [99]:
a

array([[3, 4, 4, 6],
       [5, 4, 4, 9],
       [3, 3, 3, 6]])

In [107]:
np.sort(a)

array([[3, 4, 4, 6],
       [4, 4, 5, 9],
       [3, 3, 3, 6]])

In [109]:
np.sort(a , axis=0) 

array([[3, 3, 3, 6],
       [3, 4, 4, 6],
       [5, 4, 4, 9]])

In [110]:
# Uygulama Sorular:

In [111]:
np.array([3.14, 4,6,1.2]) # çıktısı nedir? # Numpy arrayleri sabitlanmiş tip olduğu için tüm elemanlar float.

array([3.14, 4.  , 6.  , 1.2 ])

In [114]:
# array([[1., 1., 1.],
#            [1., 1., 1.]])
# bunu üretmek için:
np.ones((2,3)) # float tipinde sadece 1 lerden oluşan 2 satır 3 sutunluk array.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [115]:
# Bir NumPy array'i için boyut bilgisine nasıl erişilir?
# shape ile erişilir.

In [116]:
# Bir NumPy array’i için boyut sayısı bilgisine nasıl erişilir?
# ndim

In [117]:
# Bir NumPy array’i için toplam eleman sayısı bilgisine nasıl erişilir?
# size

In [118]:
# Bir NumPy array’i için veri tipi bilgisine nasıl erişilir?
# dtype

In [128]:
# array([[[7, 9],
# [4, 0],
# [5, 9]],

# [[4, 8],
# [6, 4],
# [4, 5]],

# [[2, 2],
# [8, 2],
# [0, 2]]])

# hangi kodu yazarsak buna benzer çıktı verilir.
#  3 satır 2 sutun ve 3 array tanımla demiş.
x=np.random.randint(10,size=(3,3,2)) # 3 array 3 satır ve 2 sutun tanımla deriz.

In [129]:
x

array([[[7, 2],
        [5, 2],
        [5, 1]],

       [[0, 0],
        [9, 8],
        [8, 2]],

       [[1, 3],
        [8, 8],
        [0, 1]]])

In [130]:
# array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x=np.arange(1,10)

In [131]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y]) # iki arrayi birleştirdi.

array([1, 2, 3, 4, 5, 6])

In [133]:
5*np.arange(1,6)

array([ 5, 10, 15, 20, 25])

In [134]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [135]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [138]:
a=np.random.randint(1,8,size=7)

In [139]:
a

array([6, 5, 1, 3, 4, 4, 5])

In [140]:
np.sort(a)

array([1, 3, 4, 4, 5, 5, 6])

İNDEX İLE ELEMANLARA ERİŞEBİLME:

In [141]:
a= np.random.randint(1,10, size=10)

In [142]:
a

array([7, 6, 8, 6, 9, 2, 7, 9, 6, 5])

In [143]:
a[0]

7

In [144]:
a[3:7]

array([6, 9, 2, 7])

In [145]:
a[1]=10

In [146]:
a

array([ 7, 10,  8,  6,  9,  2,  7,  9,  6,  5])

In [147]:
# çok boyutlu işlemlerde indexler:

In [148]:
x=np.random.randint(1,10,size=(2,5))

In [149]:
x

array([[9, 4, 2, 9, 9],
       [2, 5, 5, 9, 5]])

In [150]:
x[1,2] # 1 .inci satır 2. sutundaki eleman demek. satır ve sutun sayıları 0 dan başlayarak sayılır.

5

In [153]:
x[0,0:2] # 1 . satırdaki 1 ve 2. elemanı verir.

array([9, 4])

In [160]:
x[0:2,0:2] # iki sutundaki 1ve2.inci elemanlerı verir.

array([[9, 4],
       [2, 5]])

In [163]:
x[0:2,-1] # iki satırdaki en son elemanları verir.

array([9, 5])

In [171]:
x[0:2,2:4]

array([[2, 9],
       [5, 9]])

In [172]:
x[0:2,1:4]

array([[4, 2, 9],
       [5, 5, 9]])

In [173]:
x

array([[9, 4, 2, 9, 9],
       [2, 5, 5, 9, 5]])

In [176]:
x1=x[0:2,1:3].copy()

In [177]:
x1

array([[4, 2],
       [5, 5]])

In [179]:
x1[0]=99

In [180]:
x1 # x1 in 0. indexini değiştirdik

array([[99, 99],
       [ 5,  5]])

In [181]:
x # copy demeseydik x in kendisinde de değişme olacaktı. 

array([[9, 4, 2, 9, 9],
       [2, 5, 5, 9, 5]])

In [188]:
# Fancy index : 


In [ ]:
b=np.arange(2,15,2) # 2-15 arasında 2şer artsın demekti.

In [189]:
b

array([ 2,  4,  6,  8, 10, 12, 14])

In [190]:
[b[3],b[5],b[2]]

[8, 12, 6]

In [191]:
fancy_b=[1,2,4]

In [192]:
b[fancy_b] # index numarası 1-2-4 olan elemanları gtirir.

array([ 4,  6, 10])

In [194]:
# iki boyutta fancy:
a=np.arange(1,10).reshape((3,3))

In [195]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [203]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [204]:
a[satir,sutun]

array([2, 6])

In [207]:
a[0,[0,2]]

array([1, 3])

In [208]:
a[1,[1,2]]

array([5, 6])

In [209]:
a[0:3,[1,2]]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [210]:
x=np.arange(12).reshape(3,4)

In [211]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [212]:
x>5 # x te 5 ten büyük olanlar true küçük olanlar false olarak gösterilir.

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [213]:
x[x>5] # 5 ten büyük olanlar

array([ 6,  7,  8,  9, 10, 11])

In [221]:
x[0:1]*2

array([[0, 2, 4, 6]])

In [222]:
x[0:2]**2

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]], dtype=int32)

In [223]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [224]:
x[0:1]>=5 

array([[False, False, False, False]])

In [225]:
# ufunc fonksiyonu:

In [226]:
a=np.arange(13)

In [227]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [228]:
np.subtract(a,5) # her elemandan 5 çıkarılır.

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [229]:
np.add(a,5) # her elemana 5 ekler.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [230]:
np.multiply(a,5) # her elemanı 5 ile çarpar.

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [231]:
np.divide(a,2) # her elemanı 2 ile böler.

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [232]:
np.power(a,2) # her elemanın karesini alır.

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [233]:
np.mod(a,2) # 2 ile kalanları getir demek.

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [234]:
# np.absolute() mutlak değer alır.

In [235]:
np.sin(180) # 180 in sinus değerini alır.

-0.8011526357338304

In [236]:
np.cos(45) # 45 in cos değerini kosunüs değerini alır.

0.5253219888177297

In [243]:
np.log(16) # 16 sayısını logaritması.

2.772588722239781

In [244]:
?np # yazıp çalıştırırsanız np içinde tanımlı tüm matematiksel işlemlere ulaşabilirsiniz.

İki Bilinmeyenli Denklem Çözümleri:

In [ ]:
# 5*x0+x1=12
# x0+3*x1=10

In [246]:
# ilk önce kat sayıları np array içine yazalım
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [247]:
x=np.linalg.solve(a,b)

In [248]:
x

array([1.85714286, 2.71428571])

In [249]:
# x0 değeri=1.85714286
# x1 değeri=2.71428571

In [ ]:
# 2x2 +x1=25
# x2 +5x1=30

In [5]:
a=np.array([[2,1],[1,5]])
b=np.array([25,30])

In [6]:
x=np.linalg.solve(a,b)

In [7]:
x

array([10.55555556,  3.88888889])

In [8]:
v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 2])
v[5] # arraydeki 9 değerine erişir.

9

In [9]:
v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 9, 2])
v[-2] # 9 değerini verir.

9

In [11]:
a=np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])


In [12]:
a[1,1] # 2. satırdaki 2. elemanı verir.

5

In [14]:
a=np.array([[4, 0, 3, 0, 1],
            [9, 6, 1, 5, 9],
            [1, 9, 0, 8, 2]])

In [15]:
a[0:1] # bize ilk satırdaki tüm elemaları verir.

array([[4, 0, 3, 0, 1]])

In [16]:
a=np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])

In [17]:
a[:,2] # tüm satırlardaki 2. elemanları verir.

array([4, 0, 0])

In [18]:
a[:2,:3] # 2. satır dahil 3. sutuna kadar tüm elemanları verir.

array([[4, 7, 4],
       [2, 5, 0]])

In [20]:
a=np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])

In [22]:
[a[1], a[3]]

[3, 9]