In [1]:
# PANDAS SERİSİ OLUŞTURMAK:

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pd.Series([1,2,3,4]) # index numarası ile değerler beraber verilir.

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
seri=pd.Series([10,12,14,16])

In [11]:
type(seri)

pandas.core.series.Series

In [8]:
seri.axes # serinin index bilgilerine erişiriz.

[RangeIndex(start=0, stop=4, step=1)]

In [9]:
seri.size # eleman sayısını verir.

4

In [12]:
seri.dtype

dtype('int64')

In [13]:
seri.ndim # tek boyutlu.

1

In [14]:
seri.values # numpy şeklinde erişmek istersek.

array([10, 12, 14, 16], dtype=int64)

In [16]:
seri.head(2) # ilk 2 elemanı index numaraları ile getirir.

0    10
1    12
dtype: int64

In [18]:
seri.tail(2) # son iki elemanı getirir.

2    14
3    16
dtype: int64

In [19]:
seri

0    10
1    12
2    14
3    16
dtype: int64

In [20]:
seri=pd.Series([32,64,52,98,12,7])

In [21]:
seri

0    32
1    64
2    52
3    98
4    12
5     7
dtype: int64

In [23]:
seri=pd.Series([32,64,52,98,12,7], index=["a","b","c","d","e","f"]) # indexleri istediğimiz gibi indexleriz.

In [24]:
seri

a    32
b    64
c    52
d    98
e    12
f     7
dtype: int64

In [25]:
seri["a"]

32

In [26]:
seri["a":"c"]

a    32
b    64
c    52
dtype: int64

In [27]:
# sözlük üzerinden pandas seri oluşturma:

In [28]:
urunler={"Apple":1220,"İphone":1215,"Huawei":980}

In [29]:
seri=pd.Series(urunler)

In [30]:
seri # sözlük yapısı seriye döndü.

Apple     1220
İphone    1215
Huawei     980
dtype: int64

In [31]:
seri2=pd.concat([seri,seri])

In [32]:
seri2 # serileri birleştirdi. concat ile

Apple     1220
İphone    1215
Huawei     980
Apple     1220
İphone    1215
Huawei     980
dtype: int64

In [35]:
seri=np.random.randint(2,11, size=8)

In [36]:
seri

array([ 3,  8, 10,  3,  4,  2,  6,  2])

In [37]:
seri=pd.Series(seri)

In [38]:
seri # serimizi numpy arrayden pandasa çevirdik.

0     3
1     8
2    10
3     3
4     4
5     2
6     6
7     2
dtype: int32

In [39]:
seri[0]

3

In [40]:
seri[2:5]

2    10
3     3
4     4
dtype: int32

In [42]:
seri.index # index sayısını başlangıç ve bitşi değerini ve artış miktarını verir.

RangeIndex(start=0, stop=8, step=1)

In [44]:
seri.keys # bize anahtar elemanları index no ile gösterir.

<bound method Series.keys of 0     3
1     8
2    10
3     3
4     4
5     2
6     6
7     2
dtype: int32>

In [45]:
list(seri.items()) # index numarası ile beraber liste içinde verir.

[(0, 3), (1, 8), (2, 10), (3, 3), (4, 4), (5, 2), (6, 6), (7, 2)]

In [49]:
seri.values # sadece elemanları verir.

array([ 3,  8, 10,  3,  4,  2,  6,  2])

In [50]:
3 in seri

True

In [55]:
seri[0:3]

0     3
1     8
2    10
dtype: int32

In [56]:
seri[0]=5

In [57]:
seri

0     5
1     8
2    10
3     3
4     4
5     2
6     6
7     2
dtype: int32

In [58]:
# Pandas dataframe oluşturma:

In [59]:
a=np.arange(1,10) # tek boyutlu Dataframe

In [60]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
pd.DataFrame(a, columns=["rakamlar"]) 

rakamlar
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9

In [62]:
a=np.arange(1,13).reshape(3,4)

In [63]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
pd.DataFrame(a, columns=["index","eleman1","eleman2","eleman3"]) # sutun sayısı kadar dataframe verilir.

index  eleman1  eleman2  eleman3
0      1        2        3        4
1      5        6        7        8
2      9       10       11       12

In [68]:
df= pd.DataFrame(a,columns=["index","eleman1","eleman2","eleman3"])

In [69]:
df.columns # atadığımız dğişken adlarını gösterir.

Index(['index', 'eleman1', 'eleman2', 'eleman3'], dtype='object')

In [70]:
type(df)

pandas.core.frame.DataFrame

In [71]:
df.axes # satır 3 adet olduğu artışın 1 olduğunu değişken adlarını verdi.

[RangeIndex(start=0, stop=3, step=1),
 Index(['index', 'eleman1', 'eleman2', 'eleman3'], dtype='object')]

In [72]:
df.shape # 3 satır 4 sutun

(3, 4)

In [73]:
df.ndim # 2 boyutlu matris

2

In [74]:
df.size # eleman sayısı

12

In [75]:
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
type(df.values) # df.values her zaman array tipindedir.

numpy.ndarray

In [77]:
df.head(2)

index  eleman1  eleman2  eleman3
0      1        2        3        4
1      5        6        7        8

In [78]:
# Pandas Veri için Eleman işlemleri:

In [79]:
s1=np.random.randint(1,20, size=4)
s2=np.random.randint(1,20,size=4)
s3=np.random.randint(1,20,size=4)

In [80]:
notlar={"Ali":s1,"Veli":s2,"Hasan":s3}

In [81]:
notlar

{'Ali': array([ 2,  1,  6, 11]),
 'Veli': array([ 4, 10, 18, 11]),
 'Hasan': array([ 5,  5, 13,  4])}

In [82]:
df=pd.DataFrame(notlar)

In [83]:
df

Ali  Veli  Hasan
0    2     4      5
1    1    10      5
2    6    18     13
3   11    11      4

In [84]:
df[0:2]

Ali  Veli  Hasan
0    2     4      5
1    1    10      5

In [85]:
df[1:2]

Ali  Veli  Hasan
1    1    10      5

In [89]:
df.drop(0, axis=0) # ilk satırı siler ama kaydetmez.

Ali  Veli  Hasan
1    1    10      5
2    6    18     13
3   11    11      4

In [90]:
df.drop(0,axis=0,inplace=True)

In [91]:
df

Ali  Veli  Hasan
1    1    10      5
2    6    18     13
3   11    11      4

In [92]:
"Ali" in df

True

In [94]:
l=["Ali","Hasan","Osman","Mehmet"]
for i in l:
    print(i in df)

True
True
False
False


In [95]:
df

Ali  Veli  Hasan
1    1    10      5
2    6    18     13
3   11    11      4

In [96]:
df["Toplam"]=df["Ali"]+df["Veli"]+df["Hasan"] # her satırdaki değerler kendi arasında toplandı ve yeni bir sutun oluştu.

In [97]:
df

Ali  Veli  Hasan  Toplam
1    1    10      5      16
2    6    18     13      37
3   11    11      4      26

In [99]:
df.drop("Toplam", axis=1, inplace=True)

In [100]:
df

Ali  Veli  Hasan
1    1    10      5
2    6    18     13
3   11    11      4

In [110]:
# Gözlem ve değişken seçimi:

In [111]:
a=np.random.randint(1,30,size=(10,3))

In [113]:
df=pd.DataFrame(a, columns=("var1","var2","var3"))

In [114]:
df

var1  var2  var3
0     8    18    12
1    14    23    25
2     9    20    28
3    15    10    21
4    10    17    10
5    15     1     8
6    22    27    28
7     9     9     9
8    27    13     7
9    20    20    15

In [115]:
df.iloc[0:3]

var1  var2  var3
0     8    18    12
1    14    23    25
2     9    20    28

In [116]:
df.loc[0:3] # loc dediğimiz zaman 3 ü de dahil eder.

var1  var2  var3
0     8    18    12
1    14    23    25
2     9    20    28
3    15    10    21

In [117]:
df.iloc[1,2]

25

In [119]:
df.iloc[0:2,1]

0    18
1    23
Name: var2, dtype: int32

In [122]:
df.iloc[1:4,1:3]

var2  var3
1    23    25
2    20    28
3    10    21

In [ ]:
# genellikle iloc kullanılır.

In [ ]:
# Koşullu eleman işlemleri

In [123]:
df

var1  var2  var3
0     8    18    12
1    14    23    25
2     9    20    28
3    15    10    21
4    10    17    10
5    15     1     8
6    22    27    28
7     9     9     9
8    27    13     7
9    20    20    15

In [125]:
df.iloc[2:4,1:3]

var2  var3
2    20    28
3    10    21

In [126]:
df.var1 # sadece var1 getirir.

0     8
1    14
2     9
3    15
4    10
5    15
6    22
7     9
8    27
9    20
Name: var1, dtype: int32

In [127]:
df[df.var1>15] # var1 içindeki 15 ten büyük değerleri göster

var1  var2  var3
6    22    27    28
8    27    13     7
9    20    20    15

In [130]:
df[(df.var1>15) & (df.var3<10)] # var1 için 15 ten büyük, var3 için 10 dan küçük olanları göster.

var1  var2  var3
8    27    13     7

In [131]:
# Dataframe birleştirme işlemleri:

In [132]:
df2=df+15

In [134]:
df2

var1  var2  var3
0    23    33    27
1    29    38    40
2    24    35    43
3    30    25    36
4    25    32    25
5    30    16    23
6    37    42    43
7    24    24    24
8    42    28    22
9    35    35    30

In [136]:
pd.concat([df,df2], ignore_index=True)

var1  var2  var3
0      8    18    12
1     14    23    25
2      9    20    28
3     15    10    21
4     10    17    10
5     15     1     8
6     22    27    28
7      9     9     9
8     27    13     7
9     20    20    15
10    23    33    27
11    29    38    40
12    24    35    43
13    30    25    36
14    25    32    25
15    30    16    23
16    37    42    43
17    24    24    24
18    42    28    22
19    35    35    30

In [141]:
df2.columns=["deg1","deg2","deg3"]

In [142]:
df2.columns

Index(['deg1', 'deg2', 'deg3'], dtype='object')

In [144]:
pd.concat([df,df2], ignore_index=True)

var1  var2  var3  deg1  deg2  deg3
0    8.0  18.0  12.0   NaN   NaN   NaN
1   14.0  23.0  25.0   NaN   NaN   NaN
2    9.0  20.0  28.0   NaN   NaN   NaN
3   15.0  10.0  21.0   NaN   NaN   NaN
4   10.0  17.0  10.0   NaN   NaN   NaN
5   15.0   1.0   8.0   NaN   NaN   NaN
6   22.0  27.0  28.0   NaN   NaN   NaN
7    9.0   9.0   9.0   NaN   NaN   NaN
8   27.0  13.0   7.0   NaN   NaN   NaN
9   20.0  20.0  15.0   NaN   NaN   NaN
10   NaN   NaN   NaN  23.0  33.0  27.0
11   NaN   NaN   NaN  29.0  38.0  40.0
12   NaN   NaN   NaN  24.0  35.0  43.0
13   NaN   NaN   NaN  30.0  25.0  36.0
14   NaN   NaN   NaN  25.0  32.0  25.0
15   NaN   NaN   NaN  30.0  16.0  23.0
16   NaN   NaN   NaN  37.0  42.0  43.0
17   NaN   NaN   NaN  24.0  24.0  24.0
18   NaN   NaN   NaN  42.0  28.0  22.0
19   NaN   NaN   NaN  35.0  35.0  30.0

In [148]:
pd.concat([df,df2],join="inner") # ortak eleman olmadığı için.

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
df1=pd.DataFrame({"calisanlar":["Ali","Veli","Salih","Osman"] , "grup":["Mühendis","İK","Satıs","Muhasebe"]})

In [71]:
df2=pd.DataFrame({"calisanlar":["Ali","Veli","Salih","Osman"] , "ise_baslama":[2019,2018,2020,2021]})

In [72]:
df1

calisanlar      grup
0        Ali  Mühendis
1       Veli        İK
2      Salih     Satıs
3      Osman  Muhasebe

In [73]:
df2

calisanlar  ise_baslama
0        Ali         2019
1       Veli         2018
2      Salih         2020
3      Osman         2021

In [43]:
pd.merge(df1,df2)

Empty DataFrame
Columns: [calisanlar, grup, ise_baslama]
Index: []

In [74]:
df3=pd.merge(df1,df2)

In [75]:
df3

calisanlar      grup  ise_baslama
0        Ali  Mühendis         2019
1       Veli        İK         2018
2      Salih     Satıs         2020
3      Osman  Muhasebe         2021

In [80]:
df4=pd.DataFrame({"grup":["Muhasebe","Mühendis","Satıs"],"manager":["Hüseyin","Sadık","Kerim"]})

In [81]:
pd.merge(df3,df4)

calisanlar      grup  ise_baslama  manager
0        Ali  Mühendis         2019    Sadık
1      Salih     Satıs         2020    Kerim
2      Osman  Muhasebe         2021  Hüseyin

In [82]:
df5=pd.DataFrame({"grup":["Mühendis","İK","Satıs","Muhasebe"],"yetenekler":["Excel","Tasarım","Yapım","Sanat"]})

In [83]:
pd.merge(df1,df5)

calisanlar      grup yetenekler
0        Ali  Mühendis      Excel
1       Veli        İK    Tasarım
2      Salih     Satıs      Yapım
3      Osman  Muhasebe      Sanat

In [84]:
# Veri görselleştirme:

In [85]:
import seaborn as sns # seaborn python kütüphanesinde ki örnek veri setlerini barındırır.

In [91]:
?sns.load_dataset # çalıştırırsak bize sns kullanımını gösterir.
# https://github.com/mwaskom/seaborn-data adresinden dataset adlarına ulaşabilirsiniz.

In [94]:
df=sns.load_dataset("planets") 

In [95]:
df.head(5)

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [96]:
df.shape # 1035 satır 6 sutundan

(1035, 6)

In [97]:
df.mean() # tüm değişkenlerin ortalamalarını verir.

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [98]:
df["number"].mean() # sadece number değerlerinin ortalamasını verir.

1.7855072463768116

In [100]:
df["number"].count() 

1035

In [101]:
df["number"].max() # number içinde ki en büyük değer.

7

In [102]:
df["number"].min() # number içinde ki en küçük değer.

1

In [107]:
df["number"].sum() # number içindeki tüm değerlerin toplamını verir.

1848

In [108]:
df["number"].std() # standart sapma değerini hesaplar.

1.2409761743386767

In [109]:
df["number"].var() # varyans değerini hesaplar.

1.5400218652762578

In [110]:
df.describe().T # veri setini genel olarak görmek istersek. 25% gibi yüzdeler varyans değerleri.

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [111]:
# Pandas Gruplama İşlemleri:

In [112]:
df=pd.DataFrame({"gruplar":["A","B","C","A","B","C"], "veriler":[10,11,52,23,43,55]}, columns=["gruplar","veriler"])

In [113]:
df

gruplar  veriler
0       A       10
1       B       11
2       C       52
3       A       23
4       B       43
5       C       55

In [114]:
df.groupby("gruplar").mean() # groupby fonksiyonu parantez içine yazdığımız verisetini grup haline getirir.
# grup haline getirdikten sonra istatiksel hesapları grup içinde daha kolay yaparız.
# grupların değerlerin aritmetik ortalamasını al dedik.

veriler
gruplar         
A           16.5
B           27.0
C           53.5

In [115]:
df.groupby("gruplar").std() # grupların değerlerin standart sapmasını aldık.

veriler
gruplar           
A         9.192388
B        22.627417
C         2.121320

In [116]:
df.groupby("gruplar").var() # varyans değerlerini aldık.

veriler
gruplar         
A           84.5
B          512.0
C            4.5

In [117]:
df.groupby("gruplar").sum()

veriler
gruplar         
A             33
B             54
C            107

In [118]:
# daha büyük veri seti üzerinde istatiksel hesaplamalar:

In [119]:
df=sns.load_dataset("planets")
df.head(5) # planets çok uzun bir veri seti. üşengeçlikten sadece 5 veri üzerinde istatiksel işlem yapalım.

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [120]:
df.groupby("method")["orbital_period"].mean()
# method verisini grup içine aldık. sonrasında method grubunda orbital_period verisi üzerinde işlem yapmak istedik.
# orbital_period verisinin ortalamasını aldık.

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [121]:
df.head(5).groupby("method")["orbital_period"].mean() # sadece ilk 5 satrırndaki ortalamayı aldık.

method
Radial Velocity    549.8648
Name: orbital_period, dtype: float64

In [122]:
df.head(5).groupby("method")["mass"].var()

method
Radial Velocity    49.76222
Name: mass, dtype: float64

In [124]:
# eğer ilk 5 satırda ki tüm istatiksel işlemlere erişmek istersek:
df.head(5).describe()

number  orbital_period       mass    distance         year
count     5.0        5.000000   5.000000    5.000000     5.000000
mean      1.0      549.864800   8.362000   76.856000  2008.200000
std       0.0      265.020376   7.054234   40.630437     1.923538
min       1.0      269.300000   2.210000   19.840000  2006.000000
25%       1.0      326.030000   2.600000   56.950000  2007.000000
50%       1.0      516.220000   7.100000   77.400000  2008.000000
75%       1.0      763.000000  10.500000  110.620000  2009.000000
max       1.0      874.774000  19.400000  119.470000  2011.000000

In [125]:
# Pandas ileri seviye fonksiyonlar:

In [129]:
df=pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                "degisken1":[10,23,33,22,11,99],
                "degisken2":[100,253,333,262,111,969]},columns=["gruplar","degisken1","degisken2"])

In [130]:
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [131]:
df.groupby("gruplar").describe() # tüm istatiksel hesaplamalar var.

degisken1                                                degisken2  \
            count  mean        std   min   25%   50%   75%   max     count   
gruplar                                                                      
A             2.0  16.0   8.485281  10.0  13.0  16.0  19.0  22.0       2.0   
B             2.0  17.0   8.485281  11.0  14.0  17.0  20.0  23.0       2.0   
C             2.0  66.0  46.669048  33.0  49.5  66.0  82.5  99.0       2.0   

                                                               
          mean         std    min    25%    50%    75%    max  
gruplar                                                        
A        181.0  114.551299  100.0  140.5  181.0  221.5  262.0  
B        182.0  100.409163  111.0  146.5  182.0  217.5  253.0  
C        651.0  449.719913  333.0  492.0  651.0  810.0  969.0

In [132]:
# eğer istaiksel hesaplamamız describe içerisinde yoksa. numpy kütüphanesinden faydalanabiliriz.

In [137]:
df.groupby("gruplar").aggregate(["min", np.median,"max"])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10     16  22       100    181  262
B              11     17  23       111    182  253
C              33     66  99       333    651  969

In [138]:
df.groupby("gruplar").aggregate({"degisken1":"mean","degisken2":"std"}) # değişken1 için ortalama aldı. # değişken2 için standart sapma aldı.

degisken1   degisken2
gruplar                       
A               16  114.551299
B               17  100.409163
C               66  449.719913

In [139]:
df.groupby("gruplar").aggregate({"degisken1":"var","degisken2":"sum"})

degisken1  degisken2
gruplar                      
A               72        362
B               72        364
C             2178       1302

In [144]:
# kendimiz bir funcation oluşturduk.
def standart_sapma(x):
    return x["degisken1"].std()>9

In [145]:
df.groupby("gruplar").filter(standart_sapma)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [146]:
df.groupby("gruplar").std()>9 # böyle belirtirsek te bool döner.

degisken1  degisken2
gruplar                      
A            False       True
B            False       True
C             True       True

In [159]:
df["degisken2"].std()*9

2900.6261393016507

In [ ]:
# transform :

In [160]:
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [172]:
df_ort=df.iloc[0:6,1:6]

In [178]:
df_ort.transform(lambda x: (x-x.mean())/x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [183]:
df.apply(np.sum)

gruplar      ABCABC
degisken1       198
degisken2      2028
dtype: object

In [184]:
df.apply(np.max)

gruplar        C
degisken1     99
degisken2    969
dtype: object

In [193]:
df.groupby("gruplar")["degisken2"].std() + df.groupby("gruplar")["degisken1"].mean()

gruplar
A    130.551299
B    117.409163
C    515.719913
dtype: float64

In [194]:
import seaborn as sns

In [203]:
titanic=sns.load_dataset("titanic")
titanic.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [207]:
titanic.head(10).groupby("who")[["survived"]].mean() # titanic gemisinde yetişkinlik durumuna göre
    # hayatta kalma ortalamasını aldık.

survived
who            
child       0.5
man         0.0
woman       1.0

In [209]:
titanic.head(10).groupby("age")[["survived"]].mean() # yaş durumuna göre hayatta kalma.

survived
age           
2.0        0.0
14.0       1.0
22.0       0.0
26.0       1.0
27.0       1.0
35.0       0.5
38.0       1.0
54.0       0.0

In [218]:
titanic.head(10).groupby(["age","who"])[["survived"]].mean() # hem yaşa hem yetişkinlik durumuna göre hayatta kalma oranları.

survived
age  who            
2.0  child         0
14.0 child         1
22.0 man           0
26.0 woman         1
27.0 woman         1
35.0 man           0
     woman         1
38.0 woman         1
54.0 man           0

In [224]:
titanic.head(6).groupby(["age","who","sex"])[["survived"]].mean() # hem yaşa hem yetişkinlik hem cinsiyete göre hayatta kalma.

survived
age  who   sex             
22.0 man   male           0
26.0 woman female         1
35.0 man   male           0
     woman female         1
38.0 woman female         1

In [227]:
titanic.head(11).pivot_table("survived",["age","who","class"]) # pivot tablo olarak ilk 10 satırda bulunan
 # yaş,yetişkinlik durumu ve yolculuk edilen sınıfa göre hayatta kalma ortalamasını getirir.

survived
age  who   class           
2.0  child Third          0
4.0  child Third          1
14.0 child Second         1
22.0 man   Third          0
26.0 woman Third          1
27.0 woman Third          1
35.0 man   Third          0
     woman First          1
38.0 woman First          1
54.0 man   First          0

In [232]:
df=pd.DataFrame({"var1":[9,6,1,2,7],"var2":[2,1,5,1,3], "var3":[7,9,9,1,3], "satır":["a","b","c","d","e"]},
                columns=["satır","var1","var2","var2"])

In [233]:
df

satır  var1  var2  var2
0     a     9     2     2
1     b     6     1     1
2     c     1     5     5
3     d     2     1     1
4     e     7     3     3

In [235]:
df.iloc[2:5]

satır  var1  var2  var2
2     c     1     5     5
3     d     2     1     1
4     e     7     3     3